# Generated by Django 5.0.3 on 2024-03-20 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_app_comment_alter_app_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='app',
            field=models.ManyToManyField(blank=True, to='dashboard.app'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
