# Generated by Django 5.2 on 2025-05-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userapp_app_alter_userapp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoRunDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата запрета запуска')),
                ('apps', models.ManyToManyField(related_name='no_run_dates', to='dashboard.app', verbose_name='Приложения')),
            ],
            options={
                'verbose_name': 'Дата запрета запуска',
                'verbose_name_plural': 'Даты запрета запуска',
                'ordering': ['-date'],
            },
        ),
    ]
