# Generated by Django 5.2.3 on 2025-07-02 05:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tpir.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commondata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tpir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive_number', models.CharField(db_index=True, default='', max_length=100, verbose_name='№ предписания')),
                ('directive_date', models.DateField(verbose_name='Дата выдачи предписания')),
                ('directive_end_date', models.DateField(verbose_name='Срок устранения нарушений')),
                ('danger', models.CharField(choices=[('none', 'Нет'), ('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='none', max_length=10, verbose_name='Категория опасности')),
                ('type_tpir', models.CharField(choices=[('none', ''), ('PIR', 'ПИР'), ('SMR', 'СМР'), ('PIRSMR', 'ПИР/СМР')], default='none', max_length=10, verbose_name='Вид')),
                ('remedial_action', models.CharField(default='', max_length=100, verbose_name='Наименование мероприятия')),
                ('directive_executive', models.CharField(default='', max_length=100, verbose_name='Орган исполнительной власти')),
                ('existing_shortcomings', models.CharField(blank=True, default='', max_length=1800, verbose_name='Имеющиеся недостатки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpir_created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создатель отчёта')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commondata.department', verbose_name='Филиал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpir_updated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Отчёт ТПИР',
                'verbose_name_plural': 'Отчёты ТПИР',
                'ordering': ['-directive_date', 'facility'],
            },
        ),
        migrations.CreateModel(
            name='TpirAttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=tpir.models.tpir_files_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tpir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='tpir.tpir')),
            ],
        ),
        migrations.CreateModel(
            name='TpirFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commondata.department', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tpir',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpir.tpirfacility', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='TpirFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2100)], verbose_name='Год')),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='tpir.tpir', verbose_name='Отчёт ТПИР')),
            ],
            options={
                'verbose_name': 'Финансовая запись ТПИР',
                'verbose_name_plural': 'Финансовые записи ТПИР',
                'ordering': ['-year', 'report'],
            },
        ),
        migrations.CreateModel(
            name='TpirUserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ManyToManyField(to='commondata.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tpirfacility',
            constraint=models.UniqueConstraint(fields=('name', 'department'), name='tpir_unique_facility_name_in_department', violation_error_message='Объект с таким названием уже существует в этом филиале'),
        ),
        migrations.AddIndex(
            model_name='tpir',
            index=models.Index(fields=['directive_number'], name='tpir_tpir_directi_8a0e69_idx'),
        ),
        migrations.AddIndex(
            model_name='tpir',
            index=models.Index(fields=['directive_date', 'directive_end_date'], name='tpir_tpir_directi_7e31dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='tpirfinance',
            constraint=models.UniqueConstraint(fields=('report', 'year'), name='unique_finance_per_year'),
        ),
        migrations.AddConstraint(
            model_name='tpiruserdepartment',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_tpir_user_department'),
        ),
    ]
