# Generated by Django 5.2.3 on 2025-07-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpir',
            name='remedial_action',
            field=models.CharField(default='', max_length=250, verbose_name='Наименование мероприятия'),
        ),
    ]
