# Generated by Django 5.2.3 on 2025-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpir', '0002_alter_tpir_remedial_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpir',
            name='directive_executive',
            field=models.CharField(default='', max_length=250, verbose_name='Орган исполнительной власти'),
        ),
    ]
